all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/default/vmware_desktop/private_key
  children:
    vagrant_hosts:
      hosts:
        default: 
          ansible_host: 172.16.237.131
          ansible_port: 22
