apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command:
        [
          "wget",
          "https://raw.githubusercontent.com/Demezy/devops-labs/main/README.md",
          "-O",
          "/work-dir/README.md",
        ]
      volumeMounts:
        - name: shared-volume
          mountPath: "/work-dir"
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-volume
          mountPath: "/usr/share/nginx/html"
