apiVersion: v1
kind: Pod
metadata:
  name: multi-init
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: init-1
      image: busybox
      command: ["sh", "-c", 'echo "First init" > /work-dir/data.txt']
      volumeMounts:
        - name: shared-volume
          mountPath: "/work-dir"
    - name: init-2
      image: busybox
      command: ["sh", "-c", 'echo "Second init" >> /work-dir/data.txt']
      volumeMounts:
        - name: shared-volume
          mountPath: "/work-dir"
    - name: init-3
      image: busybox
      command: ["sh", "-c", 'echo "Third init" >> /work-dir/data.txt']
      volumeMounts:
        - name: shared-volume
          mountPath: "/work-dir"
  containers:
    - name: main-container
      image: busybox
      command:
        ["sh", "-c", "while true; do cat /work-dir/data.txt; sleep 3600; done"]
      volumeMounts:
        - name: shared-volume
          mountPath: "/work-dir"
