apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-pre-install"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: pre-install
      image: busybox
      command: ["sh", "-c", "echo Pre-install check; sleep 10"]
  restartPolicy: Never
